---
name: POE-Component-Syntax-Highlight-HTML
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: non-blocking wrapper around Syntax::Highlight::HTML
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE: 0.9999
  POE::Component::NonBlockingWrapper::Base: 0.002
  Syntax::Highlight::HTML: 0.04
build_requires:
  Test::More: 0
provides:
  POE::Component::Syntax::Highlight::HTML:
    file: lib/POE/Component/Syntax/Highlight/HTML.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
